### ISSUE TITLE
Expert waystones don't show coordinations.

### ISSUE THREAD

**Issue by Spodnie** [hetuw/OneLife#13]
Expert waystones did show coordinations in previous version of your mod (v314). Previous version is still working with the game and I keep using it because it's usefull to see expert waystones coordinates.

**Comment by hetuw** [comment]
Thank you for the report, this issue will be probably be fixed in the next version

**Comment by hetuw** [comment]
https://github.com/hetuw/OneLife/commit/4451ff4e00a9f624b659345214717c171e5f8cc1
