### ISSUE TITLE
Food pips representation

### ISSUE THREAD

**Issue by Spodnie** [hetuw/OneLife#15]
Hey, could you update the visualisation so it would actually correctly show how many pips we get from a holding food?
Here are the values (new gamma) that will be live after this week's update: https://cdn.discordapp.com/attachments/328215300279500800/700165692741255199/message.txt

I know you stopped working on your mod, so if you don't update it, at least turn off the visualisation completely pls, so it won't be confusing.

**Comment by Spodnie** [comment]
Or "new value" I'm not sure... yeah, probably new value and not "new gamma".

**Comment by hetuw** [comment]
I will turn it off in the future,
Currently jason keeps changing the values and it has become very difficult to find out the correct values. As far as I know they will also change depending on what generation you are in.
