### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by racsoa** [hetuw/OneLife#16]
Whenever I play with the mod, my computer crashes. This wouldn't be too bad but if I restart my computer and try to play again it just keeps on crashing.

**Comment by hetuw** [comment]
are you sure you have the latest version? please redownload the latest version and try again.

**Comment by hetuw** [comment]
your whole computer crashes? what exactly happens?

**Comment by racsoa** [comment]
I think that it might actually be a problem with OHOL. I tried playing with the Awbz mod and it crashed my computer as well. I'm trying to reinstall OHOL. I don't think that its a problem with the mod.

**Comment by hetuw** [comment]
It should never crash your whole computer, if the program itself crashes, it will just close, but if you have to restart your whole computer than there is also a problem with your computer.

**Comment by racsoa** [comment]
I reinstalled the base game and it hasn't crashed since. Not a bug with the mod but with the base game.

**Comment by hetuw** [comment]
ok, glad it works, i will close this
