### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by PXshadow** [hetuw/OneLife#18]
When the next client version gets published probably in a month from now. I want the automated github action system to work. I think it's the best means to keep the hetuw client alive and usable, as I don't really want to boot up a vm each time to compile the game. Also I am more than happy to welcome in contributors to the project. I will have it so github actions can also validate pull requests to make sure the code is not breaking and than I can quickly merge requests.

**Comment by Cogito** [comment]
What's the status with this? It looks like actions aren't working yet, so what needs to be done?

**Comment by PXshadow** [comment]
Hey sorry for the late reply, main thing is fixing the actions and following Wondible's method to build with actions.
