### ISSUE TITLE
The mod is not working ever since the game updated? (May,2021)

### ISSUE THREAD

**Issue by ayummy214** [hetuw/OneLife#26]
I can play the original game. When I try to play with the mod, it says to update the game through Steam, I have try everything, but the mod still doesn't work. I'm not a computer person so I don't understand how this works?

**Comment by PXshadow** [comment]
I apperciate you taking the time to make an issue, and be open about the issue and not knowing how to fix it. I just added the windows build, I hope it works @ayummy214

**Comment by ayummy214** [comment]
Thank you so much!! And thank you for your work!
