### ISSUE TITLE
Mod breaks running on diagonal roads

### ISSUE THREAD

**Issue by trevorhackman** [hetuw/OneLife#3]
Recently game was updated to make transitioning on and off diagonal roads work. When I play vanilla client diagonal road transitioning works, but on hetuw mod it doesn't.

**Comment by hetuw** [comment]
If you use the mouse it should work like the vanilla client.
But as soon as you use WASD it should break.
Is this true for you?

**Comment by trevorhackman** [comment]
No, even when using mouse transitioning on diagonal isn't working when I use the hetuw mod.

**Comment by hetuw** [comment]
ok i will test it to,
are you sure you are using the latest hetuw version?

**Comment by trevorhackman** [comment]
You were right, I didn't know I wasn't using the latest version. Everything works fine in the latest version.
