### ISSUE TITLE
Moderation Issues

### ISSUE THREAD

**Issue by NotSoShady116** [hetuw/OneLife#31]
Yikes has been trying to police the game by muting people in chat. I'd recommend getting better more fair mods, Yikes has been very biased in his moderation.

**Comment by w0wma** [comment]
This person is a known griefer, so I recommend ignoring this individual. He is known to spout hateful slurs. So what I'm assuming was, was that Yikes saw him using these slurs and muted him.

**Comment by NotSoShady116** [comment]
Nuh uh
