### ISSUE TITLE
Some Sounds are Missing

### ISSUE THREAD

**Issue by xMED0x** [hetuw/OneLife#32]
I noticed while using this mod (on multiple devices) that there're some missing sounds.
For example the sounds of babies when they pop out of their mothers, both the pop sounds and the crying baby sound are missing.
This makes it hard for mod users to be notified that they just gave birth and they will continue on with their lives without knowing.
Is there a way to enable the sounds? or does it has to be a mod fix?

**Comment by selb** [comment]
There are a number of `cache.fcz` and `bin_v368_cache.fcz` files generated by the mainline client that need to be removed for hetuw to work properly:

```
./sounds/bin_v368_cache.fcz
./reverbCache/bin_v368_cache.fcz
./objects/cache.fcz
./categories/cache.fcz
./sprites/cache.fcz
./sprites/bin_v368_cache.fcz
./transitions/cache.fcz
./animations/cache.fcz
```

To find these files, right click the game name in Steam, Manage, Browse local files.

(I had the same issue and deleted the `cache.fcz` files but didn't notice the `bin_v368` ones, and deleting all of them worked.)
