### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by Spodnie** [hetuw/OneLife#6]
Sometimes my game crashes even twice a life. Sometimes not even once but most of the time at least once per life.

Here is log from debugger:
Program received signal SIGSEGV, Segmentation fault.
0x769b9cc0 in strlen () from C:\WINDOWS\SysWOW64\msvcrt.dll
#0  0x769b9cc0 in strlen () from C:\WINDOWS\SysWOW64\msvcrt.dll
#1  0x005ed653 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)
    ()
#2  0x1f4afa28 in ?? ()
#3  0x0040ef8e in HetuwMod::onPlayerUpdate (inO=0xd4d354,
    line=0x1f01f198 "2314519 2462 0 0 0 0 0 0 0 0 876 0.24 0 0 X X 22.46 60.00 3.75 199;712;0;0;200;0 0 0 -1 0 0")
    at hetuwmod.cpp:3131
#4  0x004784fd in LivingLifePage::step (this=0x1b88dcf8) at LivingLifePage.cpp:14905
#5  0x00447715 in PageComponent::base_step (this=0x1b88dcf8) at PageComponent.cpp:54
#6  0x00449246 in GamePage::base_step (this=0x1b88dcf8) at GamePage.cpp:334
#7  0x0041746d in drawFrame (inUpdate=1 '\001') at game.cpp:1367
#8  0x0051459a in GameSceneHandler::drawScene (this=0x3070ad0) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:3169
#9  0x004e7161 in callbackDisplay () at ../../minorGems/graphics/openGL/ScreenGL_SDL.cpp:2918
#10 0x004e5bad in ScreenGL::start (this=0x306a448) at ../../minorGems/graphics/openGL/ScreenGL_SDL.cpp:2122
#11 0x005131ff in mainFunction (inNumArgs=1, inArgs=0x30688f8) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:2488
#12 0x0050e658 in SDL_main (inArgCount=1, inArgs=0x30688f8) at ../../minorGems/game/platforms/SDL/gameSDL.cpp:23
#13 0x0052b329 in console_main (argc=1, argv=0x30688f8) at ./src/main/win32/SDL_win32_main.c:315
#14 0x0052b3eb in WinMain@16 (hInst=0x400000, hPrev=hPrev@entry=0x0, szCmdLine=0x11038c6 "", sw=10)
    at ./src/main/win32/SDL_win32_main.c:398
#15 0x00608ccd in main (flags=1, cmdline=0xef1158, inst=0xef1560) at ./mingw-w64-crt/crt/crt0_c.c:18
(gdb)

Jason answered me this:

This crash is actually a bug in the mod.  I looked at their code at that spot, and they aren't handling a case correctly (if the death message arrives for a player without a death reason attached to the end).

This is on line 3131 in the mod here:

https://github.com/hetuw/OneLife/blob/master/gameSource/hetuwmod.cpp

That line assumes that deathMessage->description is not NULL, but right above there, on line 3121, deathMessage->description can be set to NULL in some cases.

I'm actually not 100% sure that this NULL string is the problem.  But something in the mod is crashing on line 3131.  Can you submit a github report for them?

I tested this case in my client, and it handles it correctly without crashing.

**Comment by hetuw** [comment]
thanks for reporting

**Comment by hetuw** [comment]
it should be fixed with the newest version 288
