### ISSUE TITLE
Vanilla Arrows + Distance

### ISSUE THREAD

**Issue by Davidj361** [hetuw/OneLife#9]
Can you add an option in the cfg or in-game to use arrows + distance instead of coordinates? It's very difficult for me as a user to compare 2 coordinates against each other in order to find my my waypoints. Perhaps give this functionality to all waypoints with mini-arrows + distance?

**Comment by hetuw** [comment]
You can click on a coord in the list and it will set all other coords relative to it, this makes it very easy to compare 2 coords
